[package]
name = "evdev-joystick"
version = "0.0.0"
edition = "2024"

[dependencies]
cfg-if = "1.0.0"
evdev-rs = "0.6.1"
libc = "0.2.172"
nix = { version = "0.30.1", features = ["ioctl"] }
thiserror = "2.0.12"
