[package]
name = "evdev-joystick-cli"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.39", features = ["derive"] }
evdev-joystick = { version = "0.0.0", path = "../evdev-joystick" }
evdev-rs = "0.6.1"
